version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: pf-postgres
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
      POSTGRES_DB: finance
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "finance"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: pf-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8000
      DATABASE_URL: postgresql+psycopg2://finance:finance@db:5432/finance
      RUN_MIGRATIONS_ON_START: "1"
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pg_data:
