[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "personal-finance"
version = "0.1.0"
description = "A personal finance management tool"
readme = "README.md"
authors = [
    {name = "Mauricio Silva", email = "maugx3@gmail.com"}
]
license = "CC0-1.0"
keywords = ["finance", "personal finance", "investment", "stocks", "bonds", "etfs"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.1.4",
    "matplotlib>=3.8.2",
    "numpy>=1.26.2",
    "seaborn>=0.13.0",
    "yfinance>=0.2.18",
    "stockdex>=1.1.0",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.2",
    "yahoofinancials>=1.20",
    "alpha_vantage>=2.3.1",
    "plotly>=5.17.0",
    "dash>=2.14.1",
    "pandas-datareader>=0.10.0",
    "fredapi>=0.5.1",
    "quantstats>=0.0.62",
    "scikit-learn>=1.3.2",
    "statsmodels>=0.14.1",
    "psycopg2-binary>=2.9.7",
    "sqlalchemy>=2.0.23",
    "alembic>=1.12.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black>=22.1.0",
    "flake8>=4.0.1",
    "isort>=5.10.1",
    "alembic>=1.10"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["personal_finance"]

[tool.black]
line-length = 79
target-version = ["py37"]

[tool.isort]
profile = "black"