# Generated by Django 5.2.7 on 2025-10-27 21:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Portfolio name', max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Optional portfolio description', verbose_name='description')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default portfolio", verbose_name='is default')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this portfolio is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(help_text='The user who owns this portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Number of shares/units held', max_digits=20, verbose_name='quantity')),
                ('average_price', models.DecimalField(blank=True, decimal_places=8, help_text='Average purchase price per share/unit', max_digits=20, null=True, verbose_name='average price')),
                ('currency', models.CharField(default='USD', help_text='Currency of the holding', max_length=3, verbose_name='currency')),
                ('acquired_at', models.DateTimeField(blank=True, help_text='When the holding was first acquired', null=True, verbose_name='acquired at')),
                ('last_transaction_at', models.DateTimeField(blank=True, help_text='Date of the last transaction', null=True, verbose_name='last transaction at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holding is still active', verbose_name='is active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this holding', verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata stored as JSON', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('asset', models.ForeignKey(help_text='The asset being held', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.asset')),
                ('user', models.ForeignKey(help_text='The user who owns this holding', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(blank=True, help_text='Portfolio containing this holding (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.portfolio')),
            ],
            options={
                'verbose_name': 'holding',
                'verbose_name_plural': 'holdings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_portfolio_name'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'asset', 'portfolio'), name='unique_user_asset_portfolio_holding'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
    ]
